export interface ISearchByChassissNumberData {
  carId: number;
  driveId: number;
  mileage: number;
  driveName: string;
  makerName: string;
  chassisNo: string;
  engineSize: number;
  registrationYear: string;
  registrationMonth: string;
  versionClass: string;
  engineCode: string;
  transmissionName: string;
  cityName: string;
  steeringName: string;
  fuelName: string;
  seats: number;
  doors: number;
  countryName: string;
  cssClass: string;
  modelCode: string;
  modelName: string;
  registeredTime: string;
  currencySymbol: string;
  isSale: number;
  promotionId: number | null;
  fuelId: number;
  fobPrice: string;
  countryId: number;
  colorName: string;
  roroFreight: number;
  roroVanning: number;
  inspection: number;
  priceAsk: number;
  imageUrl: string;
}
