import { IVehicleDetailImage } from './vehicle-detail-images.interface';
import { IVehicleDetailContactInfo } from './vehicle-detail-contact-info.interface';
import { IVehicleDetailStaffMember } from './vehicle-detail-staff-members.interface';
import { IVehicleDetailRecomendedCars } from './vehicle-detail-recomended-cars.interface';
import { IVehicleDetailStandardFeatures } from './vehicle-detail-standard-features.interface';

export interface IVehicleDetail {
  carId: number;
  driveId: number;
  mileage: number;
  driveName: string;
  makerName: string;
  chassisNo: string;
  engineSize: number;
  registrationYear: number;
  registrationMonth: number;
  versionClass: string;
  engineCode: string;
  transmissionName: string;
  cityName: string;
  steeringName: string;
  fuelName: string;
  seats: number;
  doors: number;
  countryName: string;
  cssClass: string;
  modelCode: string;
  modelName: string;
  registeredTime: string;
  currencySymbol: string;
  isSale: number;
  promotionId: null;
  fuelId: number;
  fobPrice: string;
  countryId: number;
  colorName: string;
  roroFreight: number;
  roroVanning: number;
  inspection: number;
  priceAsk: number;
  isDelivery: number;
  exteriorColor: string;
  interiorColor: string;
  whatsappNumber: string;
  purchaseDate: string;
  shipmentDate: string;
  etaDate: string;
  blNo: string;
  memo: string;
  destinationPortName: string;
  carNoInspection: number;
  manualStockNo: null;
  dubaiReserv: number;
  auctionDate: string;
  reserveDate: string;
  reseveTotalDays: string;
  futureDaysPassed: string;
  territoryYard: string;
  onTheWaySale: number;
  dutyPaid: number;
  inOrOut: number;
  transportStatus: string;
  eta: string;
  arivalDate: string;
  transShipment: string;
  ShippingCompany: string;
  auctionCompanyId: number;
  lotNo: string;
  purchasePrice: string;
  currentMukechi: string;
  bidPrice: number;
  exportCertificateNo: string;
  expiryDate: string;
  Weight: string;
  M3: string;
  engCode: string;
  receivingDate: string;
  documentPath?: string;
  imageUrl?: string;
  isDisplay?: number;
  purDate?: string;
  bidMarket?: string;
  Auction?: string;
  bidderName?: number;
  company?: string;
  makeId?: number;
  modelId?: number;
  cityId?: number;
  bodyTypeName?: string;
  price?: number;
  discountPercentage?: number;
  carAccessories?: string;
  chassisCodeName?: string;
  isGroup?: null | any;
  auctionCompanyName?: string;
  port?: string;
  saleLocation?: string;
  promotionStatus?: null | any;
  totalViews?: number;
  weight?: string;
  stockAvailableIn?: string;
  purchase?: string;
  biddingUser?: string;
  Company?: string;
  market?: string;
  autoMukechi?: null | any;
  carImages?: IVehicleDetailImage[];
  standardFeatures?: IVehicleDetailStandardFeatures[];
  contactInformation?: IVehicleDetailContactInfo[];
  staffMembers?: IVehicleDetailStaffMember[];
  RecomendedCars?: IVehicleDetailRecomendedCars[];
}
