export const ROUTES = Object.freeze({
  HOME: '/',
  ALL_STOCK: '/all_stock',
  BODY_TYPE: '/body-type',
  COUNTRY_CAR_LIST: '/stock/location',
  DUBAI_SPECIAL_COUNTRY_CAR_LIST: '/stock/special',
  AUCTION: '/stock/auction',
  AUCTIONS: '/stock/auctions',
  ABOUT_US: '/about-us',
  DETAIL: '/detail',
  JAPAN_OFFICES: '/japan-offices',
  USED_CARS: '/used-cars',
  USED_CARS_YARDS: '/used-cars/yard-location',
  SEARCH: '/used-cars/search',
  USED_CAR: '/used-car',
  USED_VEHICLES: '/used-vehicles',
  USED_VEHICLES_YARDS: '/used-vehicles/yard-location',
  DEMAND_CARS: '/demand-cars',
});
